/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package homeform;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author Abdul
 */
public class GUI extends javax.swing.JFrame {
    
      private final String url = "jdbc:mysql://localhost:3306/swe2db";
      private final String user = "root";
      private final String passwordsql = "ahh123456";

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
          try{
            Class.forName("com.mysql.cj.jdbc.Driver"); // LOAD MYSQL JDBC
        }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(this, "CANNOT LOAD JDBC!!!");
              
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Ssn_txt = new javax.swing.JTextField();
        Password_txt = new javax.swing.JPasswordField();
        Login_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FirstName_txt = new javax.swing.JTextField();
        LastName_txt = new javax.swing.JTextField();
        SSN_txt = new javax.swing.JTextField();
        PasswordR_txt = new javax.swing.JPasswordField();
        CONpassword = new javax.swing.JPasswordField();
        Registration_btn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        Age_Text = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        CheckAppo_Text = new javax.swing.JTextField();
        CheckAPPButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeform/img/Image 1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", jPanel1);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Login Information\n\n"));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("SSN :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Password :");

        Ssn_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ssn_txtActionPerformed(evt);
            }
        });

        Login_btn.setText("Login");
        Login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ssn_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(Login_btn)))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(Ssn_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(Password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Login_btn)
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jTabbedPane1.addTab("Login", jPanel2);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Registration Information"));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("First Name :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Last Name :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("SSN :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Password :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Confirm Password :");

        SSN_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSN_txtActionPerformed(evt);
            }
        });

        Registration_btn.setText("Registration");
        Registration_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registration_btnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Gender :");

        buttonGroup1.add(maleRadioButton);
        maleRadioButton.setText("Male");
        maleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(femaleRadioButton);
        femaleRadioButton.setText("Female");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Age :");

        Age_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Age_TextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(Registration_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(maleRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(femaleRadioButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Age_Text, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordR_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(CONpassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstName_txt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SSN_txt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastName_txt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(255, 255, 255))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(FirstName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(LastName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(SSN_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Age_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(maleRadioButton)
                    .addComponent(femaleRadioButton))
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordR_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CONpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(Registration_btn)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("Registeration", jPanel3);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("Contact Us by mail at : E-Hospital@gmail.com");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contact Us", jPanel4);

        jTextArea1.setBackground(new java.awt.Color(239, 239, 239));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Our Mission\nAt E-Hospital, we are committed to providing compassionate, high-quality healthcare to our community. \nOur mission is to ensure every patient receives personalized treatment in a safe and caring environment.\n\nWho We Are\nFounded in 2025,  E-Hospital has grown from a small clinic into a trusted healthcare provider in Alexandria, \nwith a team of dedicated doctors, nurses, and staff, we strive to make healthcare accessible and affordable.\n\nOur Services\nWe offer a range of medical services, including:\n   General Medicine\n   Emergency Care\n  Pediatrics\n  Laboratory & Diagnostics\n  Pharmacy\n  Dentistry\n\nOur Team has experienced healthcare professionals and Trained and compassionate Nursing & Support Staff\n\nWhy Choose Us?\n  Patient-centered care\n  Affordable treatment options\n  Modern medical equipment\n  Friendly and welcoming environment\n\nRandom Patient Testimonials\n\"The doctors here took great care of my father during his treatment. Highly recommend!\" – Alex Hugh\n\"Clean facility and quick service. Thank you!\" – Robert James");
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("About Us", jPanel5);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Enter your SSN :");

        CheckAppo_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckAppo_TextActionPerformed(evt);
            }
        });

        CheckAPPButton1.setText("Check");
        CheckAPPButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckAPPButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckAppo_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(CheckAPPButton1)))
                .addContainerGap(377, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(CheckAppo_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(CheckAPPButton1)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Check Appointment", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ssn_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ssn_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ssn_txtActionPerformed

    private void Login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_btnActionPerformed
        // TODO add your handling code here:
        
        String Ssn = Ssn_txt.getText();
        String password = Password_txt.getText();
        
        if(Ssn.isEmpty()){
            
            JOptionPane.showMessageDialog(this, "Please, Enter your SSN");
            return;
        }
        if(password.isEmpty()){
            
               JOptionPane.showMessageDialog(this, "Please, Enter your password");
                return;
        }
        
        Checklogin(Ssn,password);
       
    }//GEN-LAST:event_Login_btnActionPerformed

    private void CheckAppo_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckAppo_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckAppo_TextActionPerformed

    private void CheckAPPButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckAPPButton1ActionPerformed
        // TODO add your handling code here:
        
        String SSN = CheckAppo_Text.getText();
        
         if(SSN.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please, Enter your SSN");
            return;
        }
        CheckAppointment(SSN);
    }//GEN-LAST:event_CheckAPPButton1ActionPerformed

    private void Age_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Age_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Age_TextActionPerformed

    private void maleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioButtonActionPerformed

    private void Registration_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registration_btnActionPerformed
        // TODO add your handling code here:

        String fname = FirstName_txt.getText();
        String lname = LastName_txt.getText();
        String SSN = SSN_txt.getText();

        maleRadioButton.setActionCommand("Male");
        femaleRadioButton.setActionCommand("Female");
        String Gender = buttonGroup1.getSelection().getActionCommand();

        String password = PasswordR_txt.getText();
        String confirmpassword = CONpassword.getText();
        String age = Age_Text.getText();

        // Check if empty
        if(fname.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter your First Name");
            return;
        }
        if(lname.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter your Last Name");
            return;
        }
        if(SSN.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter your SSN");
            return;
        }
        if(SSN.length()> 14 || SSN.length() < 14){
            JOptionPane.showMessageDialog(this, "The SSN You Entered Is Longer Than 14 Digits Or Shorter Than 14 Digits!");
            return;
        }
        if(!SSN.matches("\\d+")){
            JOptionPane.showMessageDialog(this, "Please Enter Digits");
            return;
        }

        if(Gender.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Select Your Gender");
            return;
        }
        if(password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter your Password");
            return;
        }
        if(confirmpassword.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Confirm Your Password");
            return;
        }

        if(!password.matches(confirmpassword)) {
            JOptionPane.showMessageDialog(this, "Your Passwords Don't Match!!");
            return;
        }
        if(age.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter your age");
            return;
        }
        
        CheckReg(fname, lname, Gender , password , SSN, age);
    }//GEN-LAST:event_Registration_btnActionPerformed

    private void SSN_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSN_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSN_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    
    //Checking Methods
    
    
    
    public void Checklogin(String SSN, String Password){
        
        Connection con = null;
        Statement stmt = null;
        ResultSet result = null;
        String query = null;
        
        
        try{
            
            con = DriverManager.getConnection(url,user, passwordsql);
            stmt = con.createStatement();
            query = "SELECT * FROM users where SSN= '"+SSN+"' " + 
                    "and userPassword= '"+Password+"' ";
            
            result = stmt.executeQuery(query);
            
            String fname = null;
            String lname = null;
            
            if(result.next()){
                
                fname = result.getString("firstName");
                lname = result.getString("lastName");
                JOptionPane.showMessageDialog(this, "Welcome "+fname+" "+lname);
                
                PatientsGUI PGUI = new PatientsGUI();
                PGUI.setVisible(true);
                this.setVisible(false);
                
            }
            else{
                JOptionPane.showMessageDialog(this, "Invalid Username or Password!");
            }
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        finally
        {
            if(con !=null){try{con.close();}catch(Exception ex){}}
            if(stmt !=null){try{stmt.close();}catch(Exception ex){}}
            if(result !=null){try{result.close();}catch(Exception ex){}}
         }
    }
    
    public void CheckReg(String fname, String lname, String Gender, String Password, String SSN, String age){
      
        Connection con = null;
        Statement stmt = null;

        try{
            con = DriverManager.getConnection(url,user,passwordsql);
            stmt = con.createStatement();
            String query = "INSERT INTO users VALUES('"+ SSN +"','"+ Password +"', '"+ fname +"', '"+ lname +"' , '"+ Gender +"' , '"+ age +"'); ";

            int affectsRows = stmt.executeUpdate(query);

            if(affectsRows == 1 ){
                JOptionPane.showMessageDialog(this, "Successful Registration!!!");
            }
            else{
                JOptionPane.showMessageDialog(this, "ERROR!!!");
            }
        }catch(Exception e){
            if(e.getMessage().contains("Duplicate") || e.getMessage().contains("PRIMARY")) {
                JOptionPane.showMessageDialog(this, "An account with this SSN already exists.");
            } else {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        finally{
            if(con !=null){try{con.close();}catch(Exception ex){}}
            if(stmt !=null){try{stmt.close();}catch(Exception ex){}}
        }
    }
    
    public void CheckAppointment(String SSN){
        
         Connection con = null;
        Statement stmt = null;
        ResultSet result = null;
        String query = null;
        
        try{
            
            con = DriverManager.getConnection(url,user, passwordsql);
            stmt = con.createStatement();
            query = "SELECT * FROM appointments WHERE SSN = '"+ SSN +"'";
            result = stmt.executeQuery(query);
            
            String Patient_name = null;
            String  Doctor_name = null;
          
            
             if(result.next()){
                
                 Patient_name = result.getString("Patient_name");
                 Doctor_name = result.getString("doctor_name");
                String appointment_date = result.getString("appointmen_date");
                JOptionPane.showMessageDialog(this, Patient_name + "\n You Have an Appointment With " + Doctor_name + " At " + appointment_date );
             }
            else{
                JOptionPane.showMessageDialog(this, "Invalid SSN!");
            } 
        }catch(Exception x){
            JOptionPane.showMessageDialog(this, x.getMessage()); 
        }finally
        {
            if(con !=null){try{con.close();}catch(Exception ex){}}
            if(stmt !=null){try{stmt.close();}catch(Exception ex){}}
            if(result !=null){try{result.close();}catch(Exception ex){}}
         }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age_Text;
    private javax.swing.JPasswordField CONpassword;
    private javax.swing.JButton CheckAPPButton1;
    private javax.swing.JTextField CheckAppo_Text;
    private javax.swing.JTextField FirstName_txt;
    private javax.swing.JTextField LastName_txt;
    private javax.swing.JButton Login_btn;
    private javax.swing.JPasswordField PasswordR_txt;
    private javax.swing.JPasswordField Password_txt;
    private javax.swing.JButton Registration_btn;
    private javax.swing.JTextField SSN_txt;
    private javax.swing.JTextField Ssn_txt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton maleRadioButton;
    // End of variables declaration//GEN-END:variables

    void setVisiable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
