/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package homeform;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdul
 */
public class PatientsGUI extends javax.swing.JFrame  {
     
    private final String url = "jdbc:mysql://localhost:3306/swe2db";
     private final String user = "root";
     private final String passwordsql = "ahh123456";


    /**
     * Creates new form PatientsGUI
     */
    public PatientsGUI() {
        initComponents();
          try{
            Class.forName("com.mysql.cj.jdbc.Driver");
        }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(this, "CANNOT LOAD JDBC!!!");
              
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SpecializationComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        AVDocComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        AVdateComboBox1 = new javax.swing.JComboBox<>();
        AppointmentjButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        PatientsName_Text = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PatientsSSN_Text = new javax.swing.JTextField();
        BACKButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeform/img/Image 2.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Choose Specialization :");

        SpecializationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiologist", "Neurologist", "Pediatrician", "General Practitioner", "Dermatologist", "Orthopedic Surgeon", "Gynecologist", "Psychiatrist", "Oncologist", "Endocrinologist" }));
        SpecializationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpecializationComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Available Doctor : ");

        AVDocComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AVDocComboBox2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Available Date/Time :");

        AVdateComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AVdateComboBox1ActionPerformed(evt);
            }
        });

        AppointmentjButton1.setText("Make Appointment");
        AppointmentjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentjButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Patients Name :");

        PatientsName_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientsName_TextActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Patients SSN :");

        PatientsSSN_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientsSSN_TextActionPerformed(evt);
            }
        });

        BACKButton1.setText("Go Back");
        BACKButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BACKButton1)
                                .addGap(196, 196, 196)
                                .addComponent(AppointmentjButton1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AVdateComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AVDocComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SpecializationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PatientsName_Text)
                                .addComponent(PatientsSSN_Text)))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PatientsName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(PatientsSSN_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpecializationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AVDocComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AVdateComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AppointmentjButton1)
                    .addComponent(BACKButton1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SpecializationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecializationComboBoxActionPerformed
        // TODO add your handling code here:
        String SelectedSpecialization = (String) SpecializationComboBox.getSelectedItem();
        SelectedSpecialization(SelectedSpecialization);
    }//GEN-LAST:event_SpecializationComboBoxActionPerformed

    private void AppointmentjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentjButton1ActionPerformed
        // TODO add your handling code here:
        
        String SelectedSpecialization = (String) SpecializationComboBox.getSelectedItem();
        String AvailableDoc = (String) AVDocComboBox2.getSelectedItem();
        String AvailableDate_time = (String) AVdateComboBox1.getSelectedItem();
        String PatientsName = PatientsName_Text.getText();
        String PatientsSSN = PatientsSSN_Text.getText();
        
        if(SelectedSpecialization.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Choose the Specialization");
            return;
        }
        if(AvailableDoc.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Choose a Doctor");
            return;
        }
        if(AvailableDate_time.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Pick Date and Time");
            return;
        }
        if(PatientsName.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter Your Name");
            return;
        }
         if(PatientsSSN.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter your SSN");
            return;
        }
        if(PatientsSSN.length()> 14 || PatientsSSN.length()< 14){
            JOptionPane.showMessageDialog(this, "The SSN You Entered Is Longer Than 14 Digits Or Shorter Than 14 Digits!");
            
        }
        if(!PatientsSSN.matches("\\d+")){
            JOptionPane.showMessageDialog(this, "Please Enter Digits");
        }
        
        MakeAppointment(PatientsName, PatientsSSN, SelectedSpecialization,AvailableDoc, AvailableDate_time);
        
    }//GEN-LAST:event_AppointmentjButton1ActionPerformed

    private void AVdateComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AVdateComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AVdateComboBox1ActionPerformed

    private void AVDocComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AVDocComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AVDocComboBox2ActionPerformed

    private void PatientsName_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientsName_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientsName_TextActionPerformed

    private void PatientsSSN_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientsSSN_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientsSSN_TextActionPerformed

    private void BACKButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKButton1ActionPerformed
        // TODO add your handling code here:
        GUI gui = new GUI();
        gui.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BACKButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientsGUI().setVisible(true);
            }
        });
    }
    
    //Checking Methods
    
    
    public void MakeAppointment(String Patientname, String PatientSSN, String SelectedSpecialization, String AvailableDoc, String AvailableDate_time){
        
        Connection con = null;
        Statement stmt = null;
        String query = null;
        
        try{
            con = DriverManager.getConnection(url,user, passwordsql);
            stmt = con.createStatement();
            query = "INSERT INTO appointments VALUES ('"+ Patientname +"','"+ AvailableDoc +"','"+ AvailableDate_time +"','"+ PatientSSN +"')";
            
            int rowsInserted = stmt.executeUpdate(query);
            
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(null, "Appointment booked successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to book appointment.");
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }finally
        {
            if(con !=null){try{con.close();}catch(Exception ex){}}
            if(stmt !=null){try{stmt.close();}catch(Exception ex){}}
         }
    }
    
    public void SelectedSpecialization(String SelectedSpecialization){
        
        AVDocComboBox2.removeAllItems();
        
        Connection con = null;
        Statement stmt = null;
        ResultSet result = null;
        String query = null;
        
        try{
            
             con = DriverManager.getConnection(url,user, passwordsql);
             stmt = con.createStatement();
             query = "SELECT first_name, last_name FROM doctors WHERE specialization = '"+SelectedSpecialization+"'";
             result = stmt.executeQuery(query);
             
             while(result.next()){
                 
                 String doctorName = result.getString("first_name") +" "+ result.getString("last_name");
                 AVDocComboBox2.addItem(doctorName);
                 
                 AVdateComboBox1.removeAllItems();
                 
                 AVdateComboBox1.addItem("2025-05-29 10:00:00");
                 AVdateComboBox1.addItem("2025-05-30 11:30:00");
                 AVdateComboBox1.addItem("2025-05-27 13:00:00"); 
                 AVdateComboBox1.addItem("2025-05-24 14:30:00"); 
                 AVdateComboBox1.addItem("2025-05-25 16:00:00"); 
             }
            
            
        }catch(Exception ex){
             JOptionPane.showMessageDialog(this, "Error loading doctors: " + ex.getMessage());
        } finally
        {
            if(con !=null){try{con.close();}catch(Exception ex){}}
            if(stmt !=null){try{stmt.close();}catch(Exception ex){}}
            if(result !=null){try{result.close();}catch(Exception ex){}}
         }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AVDocComboBox2;
    private javax.swing.JComboBox<String> AVdateComboBox1;
    private javax.swing.JButton AppointmentjButton1;
    private javax.swing.JButton BACKButton1;
    private javax.swing.JTextField PatientsName_Text;
    private javax.swing.JTextField PatientsSSN_Text;
    private javax.swing.JComboBox<String> SpecializationComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
